checklist/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^report/', include('process.urls')),
    url(r'^admin/', admin.site.urls),
]

process/urls.py
from django.conf.urls import url

from . import views

app_name = 'process'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),    
    url(r'^(?P<pk>[0-9]+)/$', views.reportDetail.as_view(), name='reportDetail'),    
    url(r'^stage/(?P<pk>[0-9]+)/$', views.stageDetail.as_view(), name='stageDetail'),
    url(r'^(?P<stage_id>[0-9]+)/completedProcess/$', views.completedProcess, name='completedProcess'),
]

process/models.py
from django.db import models

# Create your models here.
class Stage(models.Model):
	title = models.CharField(max_length = 200)
	def __str__(self):
	    return self.title
	def all_processes_count(self):
		allProcess = self.process_set.all()
		return allProcess.count()
	def completed_processes_count(self):
		allProcess = self.process_set.all()
		completedCount = 0
		for ps in allProcess:
			if(ps.isCompleted == True):
				completedCount += 1
		return completedCount
	def isStageCompleted(self):
		if(self.all_processes_count() == self.completed_processes_count()):
			return True
		else:
			return False	

class Report(models.Model):
	title = models.CharField(max_length = 200)
	startDate = models.DateTimeField('date published')
	endDate = models.DateTimeField('date published')
	description = models.TextField(max_length = 5000, null=True, blank=True)
	stage = models.ManyToManyField(Stage)
	def __str__(self):
	    return self.title
	def completed_stages_count(self):
		allStage = self.stage.all()
		completedSatgeCount = 0
		for s in allStage:
			if(s.isStageCompleted() == True):
				completedSatgeCount +=1
		return completedSatgeCount
	def current_stage_shown(self):
		allStage = self.stage.all()
		currentSatgeId = 0
		for s in allStage:
			if(s.isStageCompleted() == False):
				currentSatgeId = s.id
				return currentSatgeId
		

class Process(models.Model):
	stage = models.ForeignKey(Stage, on_delete = models.CASCADE)
	title = models.CharField(max_length = 200)
	isCompleted = models.BooleanField(default = False)
	def __str__(self):
	    return self.title

process/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from .models import Report, Stage


class IndexView(generic.ListView):
    template_name = 'process/index.html'
    context_object_name = 'latest_report_list'

    def get_queryset(self):
	    """
	    Return the last five published questions (not including those set to be
	    published in the future).
	    """
	    return Report.objects.order_by('-endDate')[:5]

class reportDetail(generic.DetailView):
    model = Report
    template_name = 'process/reportDetail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Report.objects.all()

class stageDetail(generic.DetailView):
    model = Stage
    template_name = 'process/stageDetail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Stage.objects.all()

def completedProcess(request, stage_id):
    stage = get_object_or_404(Stage, pk=stage_id)
    try:
        selected_process = stage.process_set.get(pk=request.POST['process'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'process/stageDetail.html', {
            'stage': stage,
            'error_message': "You didn't select a process.",
        })
    else:
        selected_process.isCompleted = True
        selected_process.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('process:reportDetail', args=(stage.id,)))

process/templates/process/index.html
{% load staticfiles %} 
<script type="" src="{% static 'process/bower_components/jquery/dist/jquery.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'process/bower_components/bootstrap/dist/css/bootstrap_Lumen.css' %}" />
<script type="" src="{% static 'process/bower_components/bootstrap/dist/js/bootstrap.js' %}"></script>

<h1>Report List</h1>

{% if latest_report_list %}
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Tilte</th>
				<th>End Date</th>
				<th>Progress</th>
			</tr>
		</thead>
		<tbody>			
			{% for report in latest_report_list.all %}
			<tr>
				<td>
					<a href="{% url 'process:reportDetail' report.id %}" class="btn btn-default">{{ report.title }} <span class="glyphicon glyphicon-menu-hamburger"></span></a>
				</td>
				<td>{{ report.endDate }}</td>
				<td>
					{{ report.completed_stages_count }} / {{ report.stage.all.count }}

				</td>

			</tr>

			{% endfor %}
		</tbody>
	</table>

{% else %}
	<p>No polls are available.</p>
{% endif %}

process/templates/process/reportDetail.html
{% load staticfiles %} 
<script type="" src="{% static 'process/bower_components/jquery/dist/jquery.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'process/bower_components/bootstrap/dist/css/bootstrap_Lumen.css' %}" />
<script type="" src="{% static 'process/bower_components/bootstrap/dist/js/bootstrap.js' %}"></script>

<a href="{% url 'process:index' %}" class="btn btn-default" ><span class="glyphicon glyphicon-home" aria-hidden="true"></span> HOME</a><br>
<h1>{{ report.title }}</h1>

<b>Start Date:</b> {{ report.startDate }}<br>
<b>End Date:</b> {{ report.endDate }}<br>
<b>Description:</b> {{ report.description }}<br><br>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="progress">
  <div id="progressBarStage"class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="{{ report.completed_stages_count }}" aria-valuemin="0" aria-valuemax="{{ report.stage.all.count }}">
    {{ report.completed_stages_count }} / {{ report.stage.all.count }}
  </div>
</div>

<script>	
$(document).ready(function(){
	var compledtedStageCount = {{ report.completed_stages_count }};
	var currentWidth = "0%"
	if(compledtedStageCount == 1){
		currentWidth = "33%";
	}
	else if(compledtedStageCount == 2){
		currentWidth = "66%";
	}
	else if(compledtedStageCount == 3){
		currentWidth = "100%";
	}
    $("#progressBarStage").css({"width": currentWidth});
    
});
</script>

<!-- {{report.current_stage_shown}} -->
{% for stage in report.stage.all %}
	{% if stage.id == report.current_stage_shown %} 
    <form action="{% url 'process:completedProcess' stage.id %}" method="post">
    	{% csrf_token %}
    
    <div class="panel panel-default">
	  <!-- <div class="panel-heading"><a href="{% url 'process:stageDetail' stage.id %}">{{ stage.title }}</a></div> -->
	  <div class="panel-heading">{{ stage.title }}</div>
	  <div class="panel-body">
	  	
	    {% for process in stage.process_set.all %}

		    <ul class="list-group">
		    	<li class="list-group-item">
					{{ process.title }}
					{% if process.isCompleted == True %} 
						<span class="badge" style="background-color: #28b62c;">Completed</span>
					{% endif %}
					<div class="checkbox">
		                <label>
		                	{% if process.isCompleted == False %} 
					
		                	<input type="checkbox" name="process" id="process{{ forloop.counter }}" value="{{ process.id }}" {% if process.isCompleted %} checked {% endif %}> 
		                	<input type="submit" class="btn btn-default" value="Completed" onclick="return confirm('Are you sure?');" />
		                	{% endif %}
		                </label>
		            </div>
				</li>
		    </ul>

		    
		    
		{% endfor %}


	  </div>
	</div>
	
	
	</form>

	{% endif %}
    <!-- <label for="stage{{ forloop.counter }}"><a href="{% url 'process:stageDetail' stage.id %}">{{ stage.title }}</label><br /> -->
{% endfor %}

process/templates/process/stageDetail.html
{% load staticfiles %} 
<script type="" src="{% static 'process/bower_components/jquery/dist/jquery.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'process/bower_components/bootstrap/dist/css/bootstrap_Lumen.css' %}" />
<script type="" src="{% static 'process/bower_components/bootstrap/dist/js/bootstrap.js' %}"></script>

<h1>{{ stage.title }}</h1><br>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


{% csrf_token %}
{% for process in stage.process_set.all %}
    <!-- <input type="radio" name="stage" id="stage{{ forloop.counter }}" value="{{ stage.id }}" /> -->
    <label for="process{{ forloop.counter }}">
    	{{ process.title }}	{{ process.isCompleted }}	
    </label><br />
{% endfor %}